services:
  db_user_service:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: user_service_db
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./db_data_user_service:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uuser -padmin || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  user_service:
    build: ./user_service
    ports:
      - "5000:5000"  # Host port 5000 to container port 5000
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://user:admin@db_user_service/user_service_db
    depends_on:
      db_user_service:
        condition: service_healthy

