services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: flask_microservice
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uuser -padmin || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5


  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://user:admin@db/flask_microservice
    depends_on:
      db:
        condition: service_healthy
